run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    # default golangci-lint lints
    # NOTE: https://github.com/golangci/golangci-lint/issues/1841
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # additional lints
    - gochecknoinits
    - gofmt
    - revive # replaces golint for now
    - misspell
    - exportloopref
    - unparam

linters-settings:
  staticcheck:
    checks:
    - all
    # TODO: require go1.16 for kind and sort out migrating without breakage
    # until then, we still use io/ioutil for now
    - '-SA1019'
